import {
  AlertOctagon,
  BadgeDollarSign,
  Bell,
  BellRing,
  Building2,
  Cable,
  Calendar,
  Cloud,
  CreditCard,
  Database,
  FileCode2,
  FileText,
  Fingerprint,
  Globe,
  HardDrive,
  Headphones,
  Import,
  KeyRound,
  LayoutTemplate,
  LifeBuoy,
  Mail,
  MapPin,
  MessageSquare,
  Plug,
  Radio,
  Receipt,
  Server,
  Settings,
  ShieldAlert,
  ShieldCheck,
  SlidersHorizontal,
  Terminal,
  UserCog,
  Users,
} from 'lucide-react'

/**
 * El catálogo de Ajustes.
 *
 * Vive acá y no en la pantalla porque lo usan dos: la cuadrícula de botones y
 * la ficha de cada sección. Con la lista repetida en dos lados, agregar una
 * sección nueva significa acordarse de tocar los dos — y el día que alguien se
 * olvide, el botón va a llevar a una pantalla que dice el nombre equivocado.
 *
 * Cada entrada dice para qué sirve la sección. En las que todavía no existen,
 * eso NO es relleno: es lo que le dice a quien la abre si lo que busca va a
 * estar ahí o tiene que buscarlo en otro lado.
 */
export const AJUSTES = [
  // --- Las que ya llevan a algo que funciona ---
  {
    slug: 'importar-clientes',
    nombre: 'Importar clientes',
    icono: Import,
    a: '/clientes/importar',
    para: 'Traer la base de abonados de MikroWisp, SmartOLT o una planilla, con sus saldos y fechas.',
  },
  {
    slug: 'facturacion',
    nombre: 'Facturación',
    icono: Receipt,
    a: '/facturacion',
    para: 'Las facturas emitidas, su estado y su cobro.',
  },
  {
    slug: 'planes',
    nombre: 'Servicios y planes',
    icono: SlidersHorizontal,
    a: '/servicios/planes',
    para: 'Qué se vende, a qué precio y con qué velocidad.',
  },
  {
    slug: 'velocidades',
    nombre: 'Velocidades',
    icono: Cable,
    a: '/servicios/velocidades',
    para: 'Las traffic tables de las OLTs y los perfiles PPP de los routers.',
  },
  {
    slug: 'tickets',
    nombre: 'Tickets',
    icono: LifeBuoy,
    a: '/soporte',
    para: 'Los reclamos de los abonados y su seguimiento.',
  },
  {
    slug: 'personal',
    nombre: 'Gestión de personal',
    icono: UserCog,
    a: '/ajustes/personal',
    para: 'Quién entra al sistema: sus datos, su rol y qué puede tocar. Acá se crean, se desactivan y se les afinan los permisos uno por uno.',
  },
  {
    slug: 'auditoria',
    nombre: 'Auditoría',
    icono: ShieldAlert,
    a: '/ajustes/personal',
    para: 'Quién hizo qué, cuándo y desde qué IP. Es la pestaña de al lado del personal, porque la pregunta siempre empieza por una persona.',
  },
  {
    slug: 'tecnicos',
    nombre: 'Técnicos y cuadrillas',
    icono: Users,
    a: '/soporte/tecnicos',
    para: 'Quién puede recibir una orden de trabajo, y cómo se agrupan en cuadrillas.',
  },
  {
    slug: 'alertas',
    nombre: 'Alertas en tiempo real',
    icono: BellRing,
    a: '/ajustes/alertas',
    para: 'Avisos por WhatsApp o Telegram cuando un abonado se queda sin señal o se cae una caja. A quién avisarle, cuándo, y cuántos minutos esperar antes de molestar.',
  },
  {
    slug: 'plantillas',
    nombre: 'Editor de plantillas',
    icono: FileText,
    a: '/ajustes/plantillas',
    para: 'Todo lo que el sistema le dice al abonado: documentos que se imprimen, correos, mensajes de SMS y Telegram, y las páginas web del aviso y del corte.',
  },
  {
    slug: 'pagina-corte',
    nombre: 'Página del abonado cortado',
    icono: BellRing,
    a: '/ajustes/pagina-corte',
    para: 'Lo que ve alguien suspendido al abrir el navegador: por qué se le cortó, cuánto debe, en qué cuenta depositar y a quién avisarle que pagó.',
  },
  {
    slug: 'comisiones',
    nombre: 'Comisiones e incentivos',
    icono: BadgeDollarSign,
    a: '/ajustes/comisiones',
    para: 'Cuánto vale cada plan para el vendedor, los escalones, el bono de calidad y cuándo una venta comisiona.',
  },
  {
    slug: 'prospectos',
    nombre: 'Prospectos',
    icono: Users,
    a: '/ventas/prospectos',
    para: 'El embudo de ventas: quién preguntó, en qué quedó y a quién hay que volver a llamar.',
  },
  {
    slug: 'cobertura',
    nombre: 'Mapa de cobertura',
    icono: MapPin,
    a: '/ventas/cobertura',
    para: 'Hasta dónde se vende, y en qué cajas hay puerto libre para instalar esta semana.',
  },
  {
    slug: 'tipos-onu',
    nombre: 'Tipos de ONU',
    icono: Radio,
    a: '/onu-types',
    para: 'Los modelos de equipo: puertos, WiFi, foto y si aceptan TR069.',
  },
  {
    slug: 'routers',
    nombre: 'Routers MikroTik',
    icono: Server,
    a: '/mikrotik',
    para: 'Los routers, y el botón de reparar que deja cada uno igual a lo que dice el sistema.',
  },
  {
    slug: 'ubicaciones',
    nombre: 'Ubicaciones',
    icono: MapPin,
    a: '/clientes/mapa',
    para: 'Dónde está cada abonado y de qué caja NAP cuelga.',
  },
  {
    slug: 'monitoreo',
    nombre: 'Monitor de red',
    icono: AlertOctagon,
    a: '/monitoreo',
    para: 'Qué nodos están caídos y desde cuándo.',
  },
  {
    slug: 'cortes',
    nombre: 'Cortes y morosos',
    icono: ShieldAlert,
    a: '/bloqueos',
    para: 'Quién está cortado, por qué, y la lista que aplica el router.',
  },

  // --- Las que todavía no ---
  //
  // Llevan a su propia pantalla, que explica qué va a hacer la sección. Es
  // preferible a un botón muerto: quien la abre se entera de si lo que busca va
  // a estar ahí, y de dónde está mientras tanto.
  {
    slug: 'general',
    nombre: 'General',
    icono: Settings,
    a: '/ajustes/general',
    para: 'El nombre y el logo del sistema, y la moneda. Lo que ven todos los días quienes lo usan.',
  },
  {
    slug: 'empresa',
    nombre: 'Empresa',
    icono: Building2,
    a: '/ajustes/empresa',
    para: 'Razón social, RUC, direcciones y logo: lo que sale impreso en cada factura.',
  },
  {
    slug: 'prestador',
    nombre: 'Prestador del servicio',
    icono: ShieldCheck,
    a: '/ajustes/prestador',
    para: 'Lo que va en el contrato de adhesión: domicilio desglosado, canales de reclamo, tarifas de instalación y la fecha en que se inscribió el modelo ante la ARCOTEL. La razón social y el RUC se heredan de Empresa.',
  },
  {
    slug: 'firma',
    nombre: 'Firma del contrato',
    icono: Fingerprint,
    a: '/ajustes/firma',
    para: 'Si el abonado firma con huella y reconocimiento facial o en papel, cuánto se espera al proveedor antes de ofrecer el papel, y quién puede habilitarlo.',
  },
  {
    slug: 'correo',
    nombre: 'Servidor de correo',
    icono: Mail,
    a: '/ajustes/correo',
    para: 'La casilla desde la que salen los envíos automáticos al correo del abonado: la factura, el aviso de vencimiento y el de corte. Servidor, puerto, usuario y contraseña.',
  },
  {
    slug: 'facturacion-electronica',
    nombre: 'Facturación electrónica',
    icono: FileText,
    para: 'El certificado de firma, el ambiente —pruebas o producción— y los puntos de emisión ante el SRI.',
    mientras: 'La emisión ya funciona; lo que falta es poder configurarla desde acá.',
  },
  {
    slug: 'pasarelas',
    nombre: 'Pasarelas de pago',
    icono: CreditCard,
    para: 'Cobrar en línea con tarjeta o transferencia, y que el pago cancele la factura y levante el corte solo.',
  },
  {
    slug: 'plantillas',
    nombre: 'Editor de plantillas',
    icono: LayoutTemplate,
    para: 'Cómo se ve la factura impresa, el recibo y el correo: logo, colores y qué campos se muestran.',
  },
  {
    slug: 'plantillas-whatsapp',
    nombre: 'Plantillas de WhatsApp',
    icono: MessageSquare,
    a: '/ajustes/plantillas-whatsapp',
    para: 'Los textos aprobados por Meta. Fuera de la ventana de 24 h, WhatsApp solo entrega plantillas: sin una aprobada, el aviso de factura, el recordatorio y el de corte no salen por ahí.',
  },
  {
    slug: 'integraciones',
    nombre: 'Integraciones y API',
    icono: Plug,
    a: '/ajustes/integraciones',
    para: 'Las llaves con las que el CRM, el bot de WhatsApp y los webhooks de las pasarelas consultan facturas por cédula, registran pagos y resuelven cambios de clave. Acá se emiten, se revocan y se ve qué pidió cada uno.',
  },
  {
    slug: 'portal-cliente',
    nombre: 'Portal del cliente',
    icono: Users,
    a: '/ajustes/portal-cliente',
    para: 'El abonado entra con su cédula a ver sus facturas, reportar una falla, cambiar su clave de WiFi y corregir sus datos. Acá ves quiénes pueden entrar y los cambios que pidieron.',
  },
  {
    slug: 'push',
    nombre: 'Notificaciones push',
    icono: Bell,
    para: 'Avisar al celular del abonado cuando vence su factura o cuando se restablece el servicio.',
  },
  {
    slug: 'zendesk',
    nombre: 'Zendesk Support',
    icono: Headphones,
    para: 'Conectar los tickets del sistema con Zendesk, para los ISPs que ya lo usan.',
    mientras: 'El módulo de Tickets propio ya funciona.',
  },
  {
    slug: 'blacklist',
    nombre: 'Monitor Blacklist',
    icono: ShieldAlert,
    para: 'Avisar si alguna IP del ISP entró en una lista negra de spam, que es lo que hace que a los abonados les rebote el correo.',
  },
  {
    slug: 'cambios-masivos',
    nombre: 'Cambios masivos',
    icono: FileCode2,
    para: 'Cambiar el plan, el precio o el día de pago a muchos abonados de una vez, con vista previa antes de aplicar.',
  },
  {
    slug: 'plantillas-configuracion',
    nombre: 'Plantillas de configuración',
    icono: LayoutTemplate,
    para: 'Guardar combinaciones de perfiles y VLANs para reusarlas al dar de alta, sin volver a elegir todo.',
    mientras: 'Las plantillas de autorización de ONTs ya existen en la ficha de la OLT.',
  },
  {
    slug: 'mensajes-facturas',
    nombre: 'Mensajes de facturas',
    icono: MessageSquare,
    para: 'El texto que acompaña cada factura y cada aviso de vencimiento, con los datos del abonado.',
  },
  {
    slug: 'campos-personalizados',
    nombre: 'Campos personalizados',
    icono: FileCode2,
    para: 'Agregar campos propios a la ficha del abonado, para lo que cada ISP necesita y no está previsto.',
  },
  {
    slug: 'mensajeria',
    nombre: 'Mensajería',
    icono: MessageSquare,
    a: '/ajustes/mensajeria',
    para: 'WhatsApp, Telegram y SMS: qué bot, qué número y qué cuenta usa cada canal.',
  },
  {
    slug: 'cloud',
    nombre: 'Cloud',
    icono: Cloud,
    para: 'Respaldos automáticos fuera del servidor, y a dónde van.',
  },
  {
    slug: 'google',
    nombre: 'Google',
    icono: Globe,
    para: 'La clave de Google Maps para el mapa de abonados y el cálculo de distancias.',
  },
  {
    slug: 'base-de-datos',
    nombre: 'Base de datos',
    icono: Database,
    para: 'Respaldo, restauración y estado de la base.',
  },
  {
    slug: 'crontab',
    nombre: 'Tareas programadas',
    icono: Calendar,
    a: '/ajustes/crontab',
    para: 'A qué hora corre cada trabajo automático: la facturación, el corte de morosos, la lectura óptica.',
  },
  {
    slug: 'logs',
    nombre: 'Logs',
    icono: Terminal,
    para: 'Qué se le mandó a cada equipo y qué contestó. Es lo que permite reconstruir qué pasó cuando algo salió mal.',
    mientras: 'Se registra todo hoy, pero solo se consulta desde la base.',
  },
  {
    slug: 'sistema',
    nombre: 'Sistema',
    icono: HardDrive,
    para: 'Versión, actualizaciones y estado general.',
  },
  {
    slug: 'servidor',
    nombre: 'Servidor',
    icono: Server,
    para: 'Uso de disco, memoria y carga de la máquina donde corre el sistema.',
  },
  {
    slug: 'freeradius',
    nombre: 'FreeRADIUS',
    icono: Cable,
    para: 'Autenticar los PPPoE contra RADIUS en vez de contra los secrets del router, que es lo que hace falta cuando hay varios routers.',
  },
  {
    slug: 'licencia',
    nombre: 'Licencia',
    icono: KeyRound,
    a: '/ajustes/licencia',
    para: 'Hasta cuándo está habilitado el sistema, cuántos abonados cubre y cómo renovarlo.',
  },
]

export const buscarAjuste = (slug) => AJUSTES.find((a) => a.slug === slug)
